### PR TITLE
Add bias detection

### PR DESCRIPTION
**Pull request by Zethson**

### CODE REVIEW

**Comment by eroell** [comment]
TODOs for Eljas later

- [ ] Diabetes Dataset use one name consistently
- [ ] A1c/A1C/HbA1c use name consistently

**Comment by VladimirShitov** [comment]
<p>If you've taken it from somewhere, maybe leaving it as is and referencing the source is fine. If not, I would find some conventional approaches and list them here</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748306'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Yes, taking care of :) </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340627'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>inserted a note on that</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340651'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>I am also not sure, and vote for removing this line being restrictive to a few strong points rather than many</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340686'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Agreed - made this separation here, as it is particularly obvious in this section to me;</p><p>also removed point 4, with my "having fewer but stronger points" attitude here :)</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340719'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Indeed - this is counterintuitive. I now changed to the common, intuitive one where mild conditions have more missing data.</p><p>Although the bias, overestimating the severity and impact, does not sound as dramatic.</p><p>Nonetheless, it is a bias, and would cost resources better invested otherwise potentially</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340742'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Cool idea, just added this now</p><p> </p>

<pre class="ql-syntax" spellcheck="false">pvalue_string = "&lt; 0.001" if pvalue &lt; 0.001 else f"{pvalue:.2f}"
</pre><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340769'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>amazing, I struggled with that myself even. Added precisely that, its wonderful</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340796'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>changed to "clusters in the data"</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340824'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061449144'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>I rewrote it to</p><p> </p><p>Filtering bias emerges when the criteria used to include or exclude records in the analysis are unintendedly or unexpectedly filtering for other variables as well.</p><p> </p><p>This keeps the spirit and seems more correct to me</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748321'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>Why don't we define 4/5 properly instead of removing it? We want to add propensity score matching to ehrapy</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748306'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>Yeah, we can remove this</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340686'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>True. I'd start with people planning/performing the experiment and then the rest. Generally, I think it's useful to say that you should talk to your collaborators and have a say on experiment/cohort design.</p><p> </p><blockquote>with my "having fewer but stronger points" attitude here</blockquote><p>Fine with me!</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340719'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Zethson** [comment]
<p>Does it really matter here? I think in this specific case it just adds noise</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340769'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>haha ok. undo</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340769'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>We did have a table where the categoricals were listed before, giving that indication; this quickly gets a bit bloaty though for this many features...</p><p>At the moment lean towards keeping only that, being aware that some people would look for more detailed information</p><p> </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2061340603'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Keep the propensity score for the clinical-people; and explain inverse probability weighting.</p><p> </p><p>True, with propensity scores coming we can list that here</p><p> </p><p>- Employ propensity score matching to adjust for variables that predict receiving the treatment, thus balancing the data.</p><p>- Apply inverse probability weighting (that is, assign more weight to groups infrequently observed) to adjust the influence of observed variables that could lead to selection bias.</p><p> </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748306'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>Added explanations to numbers, and context making it more obvious I think</p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748384'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eroell** [comment]
<p>this is a very intricate example I think actually, I'm not sure I grasped that before;</p><p> </p><p>this is a scenario modelling "Regression toward the mean", where patients that have a good baseline health have a tendency to loose a lot of their extraordinary health towards a mediocre outcome: for these patients, the treatment effect is not fully visible, as it seems they have not profited much from their baseline; but in fact, they did, they would have felt worse without it.</p><p>this baseline information being hidden in the regression is the bias.</p><p> </p><p>Do we want to have this complex scenario this way in our notebook? I think we'd have to make it more clear</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/theislab/ehrapy-tutorials/pull/19/discussion/#comment-2051748455'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
